"use client"
import type { Metadata } from "next";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="159869233063-bdhr48rt9h0kj8o9umi0ikrmkk24u0on.apps.googleusercontent.com">
        <body>{children}</body>
      </GoogleOAuthProvider>
    </html>
  );
}
